apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-dep
  labels:
    app: demo
spec:
  replicas: 50
  selector:
    matchLabels:
      app: nginx-1
  template:
    metadata:
      labels:
        app: nginx-1
    spec:
      containers:
      - name: nginx
        image: nginx:1.17
        ports:
          - containerPort: 80      

